version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    image: radhey28/moneype
    container_name: backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    image: radhey28/moneype:6
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"